apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-hpa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
      - name: go
        image: marcelo27062010/go-hpa
        ports:
        - containerPort: 8000

        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"
            